name: theresoluteroad
favicon: null
layout_spectrum: 0.052899159491062164
typography_spectrum: 0.6061014118604362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8958717240020633
  lightness: 0.5002622622996569
  saturation: 0.9234417635016143
  rhythmicContrast: 0.6057025021873415
purpose: []
