name: theresoluteroad
favicon: null
layout_spectrum: 0.052899159491062164
typography_spectrum: 0.7529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f5356'
    - '#353537'
    - '#4983cc'
    - '#8cd3fd'
    - '#868074'
  brandStrength: 0.875
  lightness: 0.5002622622996569
  saturation: 0.9234417635016143
  rhythmicContrast: 0.6057025021873415
purpose: []
